apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: portfolio
  labels:
    app: portfolio
    component: secrets
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # Use: echo -n "your-secret-value" | base64
  RESEND_API_KEY: eW91cl9yZXNlbmRfYXBpX2tleV9oZXJl  # your_resend_api_key_here
  RESEND_FROM_EMAIL: bm9yZXBseUB5b3VyLWRvbWFpbi5jb20=  # noreply@your-domain.com
  RESEND_TO_EMAIL: eW91ci1lbWFpbEBleGFtcGxlLmNvbQ==    # your-email@example.com
  ANTHROPIC_API_KEY: eW91cl9hbnRocm9waWNfYXBpX2tleV9oZXJl  # your_anthropic_api_key_here
  CSRF_SECRET: eW91cl9jc3JmX3NlY3JldF9oZXJl          # your_csrf_secret_here
  SESSION_SECRET: eW91cl9zZXNzaW9uX3NlY3JldF9oZXJl      # your_session_secret_here
  SENTRY_DSN: eW91cl9zZW50cnlfZHNuX2hlcmU=             # your_sentry_dsn_here
  SENTRY_AUTH_TOKEN: eW91cl9zZW50cnlfYXV0aF90b2tlbl9oZXJl  # your_sentry_auth_token_here